import type { StoredProblem } from '@/types'

export default [
  {
    title: 'インクリメント',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3]', to: '[2, 3, 4]' },
    sheet: ['f = ■ ■'],
    choices: ['map', '(+1)', '(-1)'],
    correctAnswer: ['map', '(+1)'],
    comment: 'map で全ての要素をインクリメントします',
  },
  {
    title: '二つ目を取り出す',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3]', to: '2' },
    sheet: ['f = ■ . ■'],
    choices: ['tail', 'head', 'reverse'],
    correctAnswer: ['head', 'tail'],
    comment: '',
  },
  {
    title: '最後を取り出す',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3]', to: '3' },
    sheet: ['f = ■ . ■'],
    choices: ['tail', 'head', 'reverse'],
    correctAnswer: ['head', 'reverse'],
    comment: '',
  },
  {
    title: '長さを指定',
    env: 'GHC 8.6.5',
    map: { from: '3', to: '[1, 2, 3]' },
    sheet: ['f = ■ ■ [1..]'],
    choices: ['take', 'repeat', 'flip'],
    correctAnswer: ['flip', 'take'],
    comment: '',
  },
  {
    title: '全部反転',
    env: 'GHC 8.6.5',
    map: { from: '["abc", "def"]', to: '["cba", "fed"]' },
    sheet: ['f = ■ ■'],
    choices: ['foldr', 'map', 'reverse'],
    correctAnswer: ['map', 'reverse'],
    comment: '',
  },
  {
    title: '取って付けて',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3]', to: '[1, 2, 4]' },
    sheet: ['f = ■ . ■'],
    choices: ['tail', 'init', '(4:)', '(++[4])'],
    correctAnswer: ['(++[4])', 'init'],
    comment: '',
  },
  {
    title: '後ろを持ってくる',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3, 4, 5]', to: '[4, 5]' },
    sheet: ['f = ■ ■'],
    choices: ['take', 'drop', '3', '2'],
    correctAnswer: ['drop', '3'],
    comment: '',
  },
  {
    title: '後ろを持ってくる２',
    env: 'GHC 8.6.5',
    map: { from: '[1, 2, 3, 4, 5]', to: '[4, 5]' },
    sheet: ['f = ■ ■'],
    choices: ['dropWhile', 'drop', '(<4)', '2'],
    correctAnswer: ['dropWhile', '(<4)'],
    comment: '',
  },
  {
    title: '増殖',
    env: 'GHC 8.6.5',
    map: { from: '1', to: '[1, 11, 111, 1111, 11111]' },
    sheet: ['f = take 5 . ■ (\\x -> x*■ + 1)'],
    choices: ['iterate', 'repeat', '10', '11'],
    correctAnswer: ['iterate', '10'],
    comment: '',
  },
  {
    title: '桁は三つまで',
    env: 'GHC 8.6.5',
    map: { from: '[3, 1, 4, 1, 5]', to: '[(0, 3), (1, 1), (2, 4)]' },
    sheet: ['f = ■ ■'],
    choices: ['zip', 'take', '[0..]', '[0..2]'],
    correctAnswer: ['zip', '[0..2]'],
    comment: '',
  },
  {
    title: '自作 even',
    env: 'GHC 8.6.5',
    map: { from: '2', to: 'True' },
    sheet: ['f = (== ■) . (`mod` ■)'],
    choices: ['0', '1', '2', '3'],
    correctAnswer: ['0', '2'],
    comment: 'f n = n `mod` 2 == 0 を変形させたものです',
  },
] as StoredProblem[]
